# GiggleKat Versioning System

# GiggleKat Version
GIGGLEKAT_VERSION_MAJOR = 0.0
GIGGLEKAT_VERSION_MINOR = 1
GIGGLEKAT_VERSION_MAINTENANCE = 3
VERSION := $(GIGGLEKAT_VERSION_MAJOR).$(GIGGLEKAT_VERSION_MINOR)$(GIGGLEKAT_VERSION_MAINTENANCE)

# Set GIGGLEKAT_BUILDTYPE
ifdef GIGGLEKAT_NIGHTLY
GIGGLEKAT_BUILDTYPE := NIGHTLY
endif
ifdef GIGGLEKAT_EXPERIMENTAL
GIGGLEKAT_BUILDTYPE := EXPERIMENTAL
endif
ifdef GIGGLEKAT_RELEASE
GIGGLEKAT_BUILDTYPE := RELEASE
endif

# Set Unofficial if no buildtype set (Buildtype should ONLY be set by GIGGLEKAT Devs!)
ifdef GIGGLEKAT_BUILDTYPE
else
GIGGLEKAT_BUILDTYPE := UNOFFICIAL
GIGGLEKAT_VERSION_MAJOR := 0.0
GIGGLEKAT_VERSION_MINOR := 1
endif

# Set GIGGLEKAT version
ifdef GIGGLEKAT_RELEASE
GIGGLEKAT_VERSION := "GIGGLEKAT-v"$(VERSION)
else
GIGGLEKAT_VERSION := "$(TARGET_PRODUCT)-v$(VERSION)-$(GIGGLEKAT_BUILDTYPE)"-$(shell date +%Y%m%d-%H%M)
endif

PRODUCT_PROPERTY_OVERRIDES += \
ro.modversion=$(GIGGLEKAT_VERSION) \
ro.gigglekat.version=$(VERSION)-$(GIGGLEKAT_BUILDTYPE)
ro.bs=true \
